-- 5장 실습
SELECT *
FROM EMP
WHERE DEPTNO = 30;

-- 사원번호가 7782인 사람들을 출력해라.
SELECT *
FROM EMP
WHERE EMPNO = 7782;

-- 30번 부서이면서 직업이 세일즈맨인 사람들을 출력하라
SELECT *
FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

-- 사원번호 7499 그리고 부서번호 30인 사람
SELECT *
FROM EMP
WHERE DEPTNO = 30 AND EMPNO = 7499;

-- 부서 번호가 20번이거나 직업이 세일즈맨인 사람 출력
SELECT *
FROM EMP
WHERE DEPTNO = 20 OR JOB = 'SALESMAN'
ORDER BY DEPTNO, ENAME;

-- 문자로 연산도 가능하다 ! -> 알파벳 순이다
SELECT ENAME
FROM EMP
WHERE ENAME <= 'G'
ORDER BY ENAME;

SELECT *
FROM EMP
WHERE SAL != 3000;

-- 논리 부정 연산자 NOT
-- 위의 쿼리와 같은 문장이다.
SELECT *
FROM EMP
WHERE NOT SAL = 3000;

-- IN 연산자 (OR와 같다)
SELECT *
FROM EMP
--WHERE JOB = 'MANAGER'
--OR JOB = 'SALESMAN'
--OR JOB = 'CLERK';
WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK')
ORDER BY JOB;

-- NOT IN 연산자 
SELECT *
FROM EMP
--WHERE JOB != 'MANAGER'
--AND JOB != 'SALESMAN'
--AND JOB != 'CLERK';
WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK')
ORDER BY JOB;

-- BETWEEN A AND B 연산자 (A와 B사이의 값)
SELECT *
FROM EMP
--WHERE SAL >= 2000 AND SAL <=3000
WHERE SAL BETWEEN 2000 AND 3000
ORDER BY SAL;

SELECT *
FROM EMP
WHERE ENAME LIKE 'S%';

-- 이름에 AM이 포함되어 있는 사원을 찾아라
SELECT *
FROM EMP
WHERE ENAME LIKE '%AM%';

-- Null 관련 연산자는 'IS NULL' OR 'IS NOT NULL' 만 가능하다
SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE COMM IS NOT NULL;

-- 집합 연산자(*주의* 연산자 위아래 있는 쿼리의 셀렉트 문의 데이터가 똑같아야 한다) 
-- 1)UNION : 중복이 제한되는 합집합
-- 2)UNION ALL : 중복이 허용되는 합집합
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 20;
-- 3)MINUS : 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;
-- 4)INTERSECT : 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 10;